const mongoose = require('mongoose');
const Customers = require('./customer');
const express = require('express');
const bodyParser = require('body-parser');
const session = require('express-session');
const uuid = require('uuid'); //we require this for creating a unique session id

//we iinstall and import bcrypt for hashing and storing passwords securely
const bcrypt = require('bcrypt');
//to store passwords we need to create salts - extra random data to add to the passwords
const saltRounds = 5;
const password = "admin";

const path = require('path');
require("dotenv").config();
//an instance of the express application
const app = express();
app.use(session({
    cookie: { maxAge: 120000 }, 
    secret: 'secure-app',
    res: false,
    saveUninitialized: true,
    genid: () => uuid.v4() //this function returns a uuid which is generated by uuid.v4()
    //this function basically checks behind the scenes whether the request has a session id, if it doesn't it goes through this process 
}));

const port = 3000;

//MongoDB  connection URI and databasename
const uri = process.env.MONGO_DB;
mongoose.connect(uri, {'dbName': 'customerDB'});

//Middleware to pares JSON data
app.use(bodyParser.json())

//Serving static files from the 'frontend' directory under the '/static' routes
app.use('/static', express.static(path.join(".", 'frontend')));

//Middleware to handle URL encoded form data
// URL sEncoding replaces unsafe characters with:
// % + [two-digit hexadecimal code of the character in ASCII/UTF-8]
// Examples:
// Space " " → %20
app.use(bodyParser.urlencoded({ extended: true}))

app.post('/api/login', async (req, res) => {
    const data = req.body;
    console.log(data);

    let user_name = data['user_name'];
    let password = data['password'];

    //Querying the mongoDB 'customers' collection for matching user_name and password
    const documents = await Customers.find({user_name: user_name});

    //if a matching user is found, set the session username and serve the home page
    if(documents.length > 0){
        let result = await bcrypt.compare(password, documents[0]['password']);
        if(result){
            const genidValue = req.sessionID; //generates a unique session ID
            console.log(genidValue)
            res.cookie('username', user_name);
            res.sendFile(path.join(__dirname, 'frontend', 'home.html'));
        }else{
            res.send("Incorrect Information! Try again")
        }
    }else{
        res.send("User Information incorrect");
    }
});

app.post('/api/customer', async(req, res) => {
    const data = req.body;

    const documents = await Customers.find({user_name: data['user_name']})
    if(documents.lenth > 0){
        res.send("User already exists");
    }

    //Create a hashed password
    let hashedpwd = bcrypt.hashSync(data['password'], saltRounds);

    //Creating a new instance of the Customers model with data from the request
    const customer = new Customers({
        "user_name": data['user_name'],
        "age": data['age'],
        "password": hashedpwd,
        "email": data['email']
    });

    //Saving the new customer to the MongoDB 'customers' collection
    await customer.save();

    res.redirect('/');

});

app.get('/', async(req, res) => {
    res.sendFile(path.join(__dirname, 'frontend', 'home.html'));
});

app.get('/api/logout', async(req, res) => {
    req.session.destroy((err) => {
        if(err){
            console.error(err);
        }else {
            res.cookie('username', '', { expires: new Date(0) });
            res.redirect('/');
        }
    })
})

// Starting the server and listening on the specified port
app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});